# Generated by Django 5.1.7 on 2025-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrytext",
            name="text",
            field=models.CharField(max_length=400),
        ),
    ]
