# Generated by Django 5.1.7 on 2025-03-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree", "0002_alter_entrytext_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.JSONField()),
                (
                    "equals",
                    models.ManyToManyField(related_name="equals", to="tree.entrytext"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.entrytext"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntrySkip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.JSONField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tree.entrytext"
                    ),
                ),
            ],
        ),
    ]
